// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Calendar struct {
	ID                 int64         `json:"id"`
	SubjectMatterID    sql.NullInt32 `json:"subjectMatter_id"`
	Time               sql.NullTime  `json:"time"`
	Date               sql.NullTime  `json:"date"`
	Available          sql.NullBool  `json:"available"`
	FilledStudentID    sql.NullInt32 `json:"filled_student_id"`
	ProfessionalUserID sql.NullInt32 `json:"professionalUser_id"`
}

type Phone struct {
	ID          int64          `json:"id"`
	CountryCode sql.NullInt32  `json:"country_code"`
	AreaCore    sql.NullInt32  `json:"area_core"`
	Number      sql.NullInt32  `json:"number"`
	Type        sql.NullString `json:"type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProfessionalInformation struct {
	ID                int64          `json:"id"`
	ExperiencePeriod  sql.NullString `json:"experience_period"`
	OcupationArea     sql.NullString `json:"ocupation_area"`
	University        sql.NullString `json:"university"`
	GraduationDiploma sql.NullString `json:"graduation_diploma"`
	Validate          sql.NullBool   `json:"validate"`
	GraduationCountry sql.NullString `json:"graduation_country"`
	GraduationCity    sql.NullString `json:"graduation_city"`
	GraduationState   sql.NullString `json:"graduation_state"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type ProfessionalUser struct {
	ID                        int64          `json:"id"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	Name                      sql.NullString `json:"name"`
	Username                  sql.NullString `json:"username"`
	Password                  sql.NullString `json:"password"`
	Gender                    sql.NullString `json:"gender"`
	Email                     sql.NullString `json:"email"`
	DateOfBirth               sql.NullTime   `json:"date_of_birth"`
	Cpf                       sql.NullInt32  `json:"cpf"`
	ImageID                   sql.NullInt64  `json:"image_id"`
	PhoneID                   sql.NullInt64  `json:"phone_id"`
	ProfessionalInformationID sql.NullInt64  `json:"professional_information_id"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
	SubjectMatterID           sql.NullInt32  `json:"subjectMatter_id"`
	SubjectMatterClassID      sql.NullInt32  `json:"subjectMatter_class_id"`
	ClassHourPrice            sql.NullString `json:"class_hour_price"`
	CalendarID                sql.NullInt32  `json:"calendar_id"`
}

type ProfessionalUserSubjectMatter struct {
	ProfessionalUserID int64 `json:"professionalUser_id"`
	SubjectMatterID    int64 `json:"subjectMatter_id"`
}

type ResponsibleStudent struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Gender      sql.NullString `json:"gender"`
	Email       sql.NullString `json:"email"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
	Cpf         sql.NullInt32  `json:"cpf"`
	PhoneID     sql.NullInt64  `json:"phone_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type StudentUser struct {
	ID                   int64          `json:"id"`
	Username             sql.NullString `json:"username"`
	Password             sql.NullString `json:"password"`
	Name                 sql.NullString `json:"name"`
	DateOfBirth          sql.NullTime   `json:"date_of_birth"`
	Gender               sql.NullString `json:"gender"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	ResponsibleStudentID sql.NullInt32  `json:"responsible_student_id"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	SubjectMatterClassID sql.NullInt32  `json:"subjectMatter_class_id"`
	CalendarID           sql.NullInt32  `json:"calendar_id"`
}

type SubjectMatter struct {
	ID        int64          `json:"id"`
	Title     sql.NullString `json:"title"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Category  sql.NullString `json:"category"`
	Abstract  sql.NullString `json:"abstract"`
}

type SubjectMatterCalendar struct {
	SubjectMatterID int64 `json:"subjectMatter_id"`
	CalendarID      int64 `json:"calendar_id"`
}

type SubjectMatterClass struct {
	ID                 int64          `json:"id"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	SubjectMatterID    sql.NullInt32  `json:"subjectMatter_id"`
	ProfessionalID     sql.NullInt32  `json:"professional_id"`
	Durantion          sql.NullInt32  `json:"durantion"`
	EnrollmentDate     sql.NullTime   `json:"enrollment_date"`
	EnrollmentTime     sql.NullTime   `json:"enrollment_time"`
	Cancellation       sql.NullBool   `json:"cancellation"`
	CancellationReason sql.NullString `json:"cancellation_reason"`
	StudentAttendence  sql.NullBool   `json:"student_attendence"`
	StudyMaterial      sql.NullString `json:"study_material"`
	TestingExam        sql.NullString `json:"testing_exam"`
}
